sudo: required

language: haskell

cache:
  directories:
      - $HOME/.stack/

before_install:
- mkdir -p ~/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- travis_retry curl -skL https://www.stackage.org/stack/osx-x86_64 | tar xz --strip-components=1 --include '*/stack' -C ~/.local/bin

install:
- stack --no-terminal --skip-ghc-check setup
- stack build --no-terminal --skip-ghc-check --only-snapshot

script:
- stack --no-terminal --skip-ghc-check test
