sudo: false

language: haskell

cache:
  directories:
      - $HOME/.stack/

before_install:
  # Download and unpack the stack executable
  - mkdir -p ~/.local/bin
  - export PATH=$HOME/.local/bin:$PATH
  - travis_retry curl -L https://www.stackage.org/stack/osx-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

before_install:
    - export PATH=/opt/ghc/7.10.2/bin:$PATH

install:
- stack --no-terminal --skip-ghc-check setup
- stack build --no-terminal --skip-ghc-check --only-snapshot

script:
- stack --no-terminal --skip-ghc-check test
