defaults: &defaults
  pre:
    - wget https://github.com/commercialhaskell/stack/releases/download/v1.2.0/stack-1.2.0-linux-x86_64.tar.gz -O /tmp/stack.tar.gz
    - mkdir /tmp/stack/
    - tar -xvzf /tmp/stack.tar.gz -C /tmp/stack/
    - sudo mv /tmp/stack/stack-1.2.0-linux-x86_64/stack /usr/bin/stack  
  working_directory: ~/build
  machine: true
  steps:
    - checkout

    - run:
        command: git submodule sync --recursive
        
    - run:
        command: git submodule update --recursive --init
        
    - run:
        name: Write provided stack.yaml with predictable name
        command: cp ${STACK_FILE} stack-build.txt

    - run:
        name: Figure out resolver for better caching
        command: grep '^resolver:' stack-build.txt > resolver.txt

    - run:
        name: Create a composite cabal file for changes detection
        command: find . -name "*.cabal" | grep -v "stack-work" | xargs cat > all-cabal.txt

    - restore_cache:
        keys:
          - stack-cache-08-{{ arch }}-{{ .Environment.CIRCLE_JOB }}-{{ checksum "stack-build.txt" }}-{{ checksum "all-cabal.txt" }}
          - stack-cache-08-{{ arch }}-{{ .Environment.CIRCLE_JOB }}-{{ checksum "stack-build.txt" }}
          - stack-cache-08-{{ arch }}-{{ .Environment.CIRCLE_JOB }}-{{ checksum "resolver.txt" }}

    - run:
        name: Stack setup
        command: stack -j 2 --stack-yaml=${STACK_FILE} setup

    - run:
        name: Build
        command: stack -j 2 --stack-yaml=${STACK_FILE} install

    - run:
        name: Test
        command: stack -j 2 --stack-yaml=${STACK_FILE} test --dump-logs
        no_output_timeout: 120m

    - store_artifacts:
        path: test-logs

version: 2
jobs:
  ghc-8.4.3:
    environment:
      - STACK_FILE: "stack.yaml"
    <<: *defaults

  ghc-nightly:
    environment:
      - STACK_FILE: "stack.yaml"
    <<: *defaults

workflows:
  version: 2
  multiple-ghcs:
    jobs:
      - ghc-8.4.3
      - ghc-nightly
